# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connectWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConnectWindow(object):
    """Класс окна подключения"""
    def setupUi(self, ConnectWindow):
        ConnectWindow.setObjectName("ConnectWindow")
        ConnectWindow.setEnabled(True)
        ConnectWindow.resize(1440, 838)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ConnectWindow.sizePolicy().hasHeightForWidth())
        ConnectWindow.setSizePolicy(sizePolicy)
        ConnectWindow.setMinimumSize(QtCore.QSize(1440, 838))
        ConnectWindow.setMaximumSize(QtCore.QSize(1440, 838))
        ConnectWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        ConnectWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        ConnectWindow.setStyleSheet("background-image: url(:/imgs/authBackground.png);")
        self.centralwidget = QtWidgets.QWidget(ConnectWindow)
        self.centralwidget.setStyleSheet("color:FFFFFF\n"
                                         "")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(429, 211, 582, 417))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(582, 417))
        self.widget.setMaximumSize(QtCore.QSize(582, 417))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("QWidget { /* Auto layout */\n"
                                  "\n"
                                  "\n"
                                  "position: absolute;\n"
                                  "width: 582px;\n"
                                  "height: 439px;\n"
                                  "left: 80px;\n"
                                  "top: 60px;\n"
                                  "\n"
                                  "background: #FFFFFF;\n"
                                  "border-radius: 6px; }")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(70, 24, 70, 50)
        self.verticalLayout.setSpacing(24)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(81)
        sizePolicy.setVerticalStretch(149)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(149, 81))
        self.label.setMaximumSize(QtCore.QSize(149, 81))
        self.label.setStyleSheet("image: url(:/imgs/logo-gazprom-neft.png)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(16)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.devices_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devices_label.sizePolicy().hasHeightForWidth())
        self.devices_label.setSizePolicy(sizePolicy)
        self.devices_label.setStyleSheet("#devices_label{\n"
                                         "font-family: \'Segoe UI\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 18px;\n"
                                         "line-height: 150%;\n"
                                         "color: rgba(0, 32, 51, 0.6);\n"
                                         "}")
        self.devices_label.setTextFormat(QtCore.Qt.PlainText)
        self.devices_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.devices_label.setIndent(0)
        self.devices_label.setObjectName("devices_label")
        self.verticalLayout_2.addWidget(self.devices_label)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.devices_comboBox = QtWidgets.QComboBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devices_comboBox.sizePolicy().hasHeightForWidth())
        self.devices_comboBox.setSizePolicy(sizePolicy)
        self.devices_comboBox.setMinimumSize(QtCore.QSize(0, 48))
        self.devices_comboBox.setMaximumSize(QtCore.QSize(16777215, 48))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.devices_comboBox.setFont(font)
        self.devices_comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.devices_comboBox.setStyleSheet("#devices_comboBox{\n"
                                            "\n"
                                            "height:48px;\n"
                                            "/* control-default/bg */\n"
                                            "font-family: \'Segoe UI\';\n"
                                            "font-weight: 400;\n"
                                            "font-style: normal;\n"
                                            "font-size: 18px;\n"
                                            "\n"
                                            "padding-left: 13px;\n"
                                            "/* control-default/bg-border */\n"
                                            "\n"
                                            "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                            "border-radius: 4px;\n"
                                            "\n"
                                            "color: black;\n"
                                            "outline: 0px;\n"
                                            "}\n"
                                            "\n"
                                            "#devices_comboBox::drop-down{\n"
                                            "border: 0px;\n"
                                            "width: 48px;\n"
                                            "}\n"
                                            "\n"
                                            "#devices_comboBox::down-arrow {\n"
                                            "    image: url(:/imgs/arrowComboBox.png);\n"
                                            "width: 48px;\n"
                                            "}\n"
                                            "\n"
                                            "#devices_comboBox::on {\n"
                                            "border: 1px solid #0091FF;\n"
                                            "outline: 0px;\n"
                                            "}\n"
                                            "\n"
                                            "#devices_comboBox QListView {\n"
                                            "outline-color: #fff;\n"
                                            "background-color: #fff;\n"
                                            "\n"
                                            "font-family: \'Segoe UI\';\n"
                                            "font-weight: 400;\n"
                                            "font-style: normal;\n"
                                            "font-size: 18px;\n"
                                            "\n"
                                            "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                            "\n"
                                            "border-radius: 4px;\n"
                                            "margin-top: 7px;\n"
                                            "outline: 0px;\n"
                                            "\n"
                                            "selection-background-color: rgba(0, 32, 51, 0.05);\n"
                                            "selection-color: black;\n"
                                            "\n"
                                            "padding-top:10px;\n"
                                            "padding-bottom:10px;\n"
                                            "padding-left:12px;\n"
                                            "padding-right:12px;\n"
                                            "\n"
                                            "}\n"
                                            "\n"
                                            "#devices_comboBox QAbstractItemView::text {\n"
                                            "\n"
                                            "padding:10px;\n"
                                            "}\n"
                                            "\n"
                                            "\n"
                                            "\n"
                                            "\n"
                                            "")
        self.devices_comboBox.setEditable(False)
        self.devices_comboBox.setMaxVisibleItems(10)
        self.devices_comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.devices_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.devices_comboBox.setIconSize(QtCore.QSize(48, 48))
        self.devices_comboBox.setDuplicatesEnabled(False)
        self.devices_comboBox.setFrame(False)
        self.devices_comboBox.setObjectName("devices_comboBox")
        self.devices_comboBox.addItem("")
        self.devices_comboBox.addItem("")
        self.devices_comboBox.addItem("")
        self.verticalLayout_4.addWidget(self.devices_comboBox)
        self.connect_statusLabel = QtWidgets.QLabel(self.widget_2)
        self.connect_statusLabel.setStyleSheet("#connect_statusLabel{\n"
                                               "min-height:14px;\n"
                                               "max-height:14px;\n"
                                               "height:14px;\n"
                                               "padding-left:13px;\n"
                                               "color: #EB3333;\n"
                                               "font-family: \'Segoe UI\';\n"
                                               "font-style: normal;\n"
                                               "font-weight: 400;\n"
                                               "font-size: 12px;\n"
                                               "line-height: 120%;\n"
                                               "}")
        self.connect_statusLabel.setText("")
        self.connect_statusLabel.setObjectName("connect_statusLabel")
        self.verticalLayout_4.addWidget(self.connect_statusLabel)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.connect_pushButton = QtWidgets.QPushButton(self.widget)
        self.connect_pushButton.setStyleSheet("#connect_pushButton{\n"
                                              "width: 441px;\n"
                                              "height: 40px;\n"
                                              "\n"
                                              "/* control-primary/bg */\n"
                                              "\n"
                                              "\n"
                                              "background: #0078D2;\n"
                                              "border-radius: 20px;\n"
                                              "\n"
                                              "\n"
                                              "font-family: \'Segoe UI\';\n"
                                              "font-style: normal;\n"
                                              "font-weight: 400;\n"
                                              "font-size: 16px;\n"
                                              "line-height: 40px;\n"
                                              "\n"
                                              "\n"
                                              "/* control-primary/typo */\n"
                                              "\n"
                                              "color: #FFFFFF;\n"
                                              "}\n"
                                              "\n"
                                              "#connect_pushButton::hover{\n"
                                              "background: rgb(0, 134, 229);\n"
                                              "\n"
                                              "}\n"
                                              "\n"
                                              "#connect_pushButton::pressed{\n"
                                              "\n"
                                              "border: 4px solid rgb(0, 101, 173);\n"
                                              "}")
        self.connect_pushButton.setAutoDefault(False)
        self.connect_pushButton.setDefault(False)
        self.connect_pushButton.setFlat(False)
        self.connect_pushButton.setObjectName("connect_pushButton")
        self.verticalLayout_3.addWidget(self.connect_pushButton)
        self.updateDevices_pushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateDevices_pushButton.sizePolicy().hasHeightForWidth())
        self.updateDevices_pushButton.setSizePolicy(sizePolicy)
        self.updateDevices_pushButton.setStyleSheet("#updateDevices_pushButton{\n"
                                                    "width: 441px;\n"
                                                    "height: 40px;\n"
                                                    "\n"
                                                    "/* control-primary/bg */\n"
                                                    "\n"
                                                    "\n"
                                                    "background: #fff;\n"
                                                    "border-radius: 20px;\n"
                                                    "border: 1px solid #0078D2;\n"
                                                    "\n"
                                                    "\n"
                                                    "font-family: \'Segoe UI\';\n"
                                                    "font-style: normal;\n"
                                                    "font-weight: 400;\n"
                                                    "font-size: 16px;\n"
                                                    "line-height: 40px;\n"
                                                    "\n"
                                                    "\n"
                                                    "/* control-primary/typo */\n"
                                                    "\n"
                                                    "color: #0078D2;\n"
                                                    "}\n"
                                                    "\n"
                                                    "#updateDevices_pushButton::hover{\n"
                                                    "background: rgb(205, 238, 255);\n"
                                                    "\n"
                                                    "}\n"
                                                    "\n"
                                                    "#updateDevices_pushButton::pressed{\n"
                                                    "\n"
                                                    "border: 4px solid rgb(139, 205, 255);\n"
                                                    "}")
        self.updateDevices_pushButton.setAutoDefault(False)
        self.updateDevices_pushButton.setDefault(False)
        self.updateDevices_pushButton.setFlat(False)
        self.updateDevices_pushButton.setObjectName("updateDevices_pushButton")
        self.verticalLayout_3.addWidget(self.updateDevices_pushButton)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        ConnectWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ConnectWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 26))
        self.menubar.setObjectName("menubar")
        ConnectWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ConnectWindow)
        self.statusbar.setObjectName("statusbar")
        ConnectWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ConnectWindow)
        QtCore.QMetaObject.connectSlotsByName(ConnectWindow)

    def retranslateUi(self, ConnectWindow):
        _translate = QtCore.QCoreApplication.translate
        ConnectWindow.setWindowTitle(_translate("ConnectWindow", "MainWindow"))
        self.devices_label.setText(_translate("ConnectWindow", "Доступные устройства"))
        self.devices_comboBox.setCurrentText(_translate("ConnectWindow", "Выберите устройство..."))
        self.devices_comboBox.setItemText(0, _translate("ConnectWindow", "Выберите устройство..."))
        self.devices_comboBox.setItemText(1, _translate("ConnectWindow", "COM1"))
        self.devices_comboBox.setItemText(2, _translate("ConnectWindow", "COM2"))
        self.connect_pushButton.setText(_translate("ConnectWindow", "Подключить устройство"))
        self.updateDevices_pushButton.setText(_translate("ConnectWindow", "Обновить устройства"))


import resources_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ConnectWindow = QtWidgets.QMainWindow()
    ui = Ui_ConnectWindow()
    ui.setupUi(ConnectWindow)
    ConnectWindow.show()
    sys.exit(app.exec_())
