# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'creSampWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_creSampWindow(object):
    """Класс диалогового окна создания эксперимента"""
    def setupUi(self, creSampWindow):
        creSampWindow.setObjectName("creSampWindow")
        creSampWindow.resize(1182, 610)
        creSampWindow.setStyleSheet("background: #fff;\n"
                                    "border-radius: 8px;")
        self.verticalLayout = QtWidgets.QVBoxLayout(creSampWindow)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(32)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(creSampWindow)
        self.label.setStyleSheet("/* XL */\n"
                                 "\n"
                                 "font-family: \'Inter\';\n"
                                 "font-style: normal;\n"
                                 "font-weight: 400;\n"
                                 "font-size: 20px;\n"
                                 "line-height: 150%;\n"
                                 "\n"
                                 "/* bg/tone */\n"
                                 "\n"
                                 "color: rgba(0, 32, 51, 0.85);\n"
                                 "\n"
                                 "")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.widget = QtWidgets.QWidget(creSampWindow)
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(32)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupName_label = QtWidgets.QLabel(self.widget_4)
        self.groupName_label.setStyleSheet("width: 152px;\n"
                                           "height: 21px;\n"
                                           "\n"
                                           "/* S */\n"
                                           "\n"
                                           "font-family: \'Inter\';\n"
                                           "font-style: normal;\n"
                                           "font-weight: 400;\n"
                                           "font-size: 14px;\n"
                                           "line-height: 150%;\n"
                                           "/* identical to box height, or 21px */\n"
                                           "\n"
                                           "/* typo/primary */\n"
                                           "\n"
                                           "color: #002033;")
        self.groupName_label.setObjectName("groupName_label")
        self.verticalLayout_2.addWidget(self.groupName_label)
        self.groupName_lineEdit = QtWidgets.QLineEdit(self.widget_4)
        self.groupName_lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.groupName_lineEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupName_lineEdit.setStyleSheet("\n"
                                              "padding: 0px 11px;\n"
                                              "gap: 12px;\n"
                                              "\n"
                                              "position: absolute;\n"
                                              "height: 40px;\n"
                                              "left: 0px;\n"
                                              "right: 0px;\n"
                                              "top: 0px;\n"
                                              "\n"
                                              "/* control-default/bg */\n"
                                              "\n"
                                              "background: #FFFFFF;\n"
                                              "/* control-default/bg-border */\n"
                                              "\n"
                                              "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                              "border-radius: 4px;\n"
                                              "\n"
                                              "\n"
                                              "font-family: \'Segoe UI\';\n"
                                              "font-style: normal;\n"
                                              "font-weight: 400;\n"
                                              "font-size: 16px;\n"
                                              "line-height: 150%;")
        self.groupName_lineEdit.setObjectName("groupName_lineEdit")
        self.verticalLayout_2.addWidget(self.groupName_lineEdit)
        self.gridLayout_2.addWidget(self.widget_4, 0, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.widget_2)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.sampleNum_label = QtWidgets.QLabel(self.widget_6)
        self.sampleNum_label.setStyleSheet("width: 152px;\n"
                                           "height: 21px;\n"
                                           "\n"
                                           "/* S */\n"
                                           "\n"
                                           "font-family: \'Inter\';\n"
                                           "font-style: normal;\n"
                                           "font-weight: 400;\n"
                                           "font-size: 14px;\n"
                                           "line-height: 150%;\n"
                                           "/* identical to box height, or 21px */\n"
                                           "\n"
                                           "/* typo/primary */\n"
                                           "\n"
                                           "color: #002033;")
        self.sampleNum_label.setObjectName("sampleNum_label")
        self.verticalLayout_4.addWidget(self.sampleNum_label)
        self.sampleNum_spinBox = QtWidgets.QSpinBox(self.widget_6)
        self.sampleNum_spinBox.setEnabled(False)
        self.sampleNum_spinBox.setMinimumSize(QtCore.QSize(0, 40))
        self.sampleNum_spinBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.sampleNum_spinBox.setStyleSheet("QSpinBox\n"
                                             "{\n"
                                             "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                             "border-radius: 4px;\n"
                                             "height: 40px;\n"
                                             "\n"
                                             "padding: 0px 11px;\n"
                                             "gap: 12px;\n"
                                             "\n"
                                             "font-family: \'Segoe UI\';\n"
                                             "font-style: normal;\n"
                                             "font-weight: 400;\n"
                                             "font-size: 16px;\n"
                                             "line-height: 22px;\n"
                                             "}\n"
                                             "\n"
                                             "\n"
                                             "QSpinBox::up-button {\n"
                                             "width:40px;\n"
                                             "image:url(:/imgs/up-arrow.png);\n"
                                             "padding-top:4px;\n"
                                             "}\n"
                                             "\n"
                                             "QSpinBox::down-button {\n"
                                             "image:url(:/imgs/down-arrow.png);\n"
                                             "width:40px;\n"
                                             "padding-bottom:4px;\n"
                                             "}\n"
                                             "\n"
                                             "\n"
                                             "QSpinBox::up-button:pressed {\n"
                                             "width:40px;\n"
                                             "image:url(:/imgs/up-arrow.png);\n"
                                             "padding-top:4px;\n"
                                             "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                             "}\n"
                                             "\n"
                                             "QSpinBox::down-button:pressed {\n"
                                             "image:url(:/imgs/down-arrow.png);\n"
                                             "width:40px;\n"
                                             "padding-bottom:4px;\n"
                                             "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                             "}")
        self.sampleNum_spinBox.setSuffix("")
        self.sampleNum_spinBox.setProperty("value", 1)
        self.sampleNum_spinBox.setObjectName("sampleNum_spinBox")
        self.verticalLayout_4.addWidget(self.sampleNum_spinBox)
        self.gridLayout_2.addWidget(self.widget_6, 4, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.expType_label = QtWidgets.QLabel(self.widget_5)
        self.expType_label.setStyleSheet("width: 152px;\n"
                                         "height: 21px;\n"
                                         "\n"
                                         "/* S */\n"
                                         "\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 14px;\n"
                                         "line-height: 150%;\n"
                                         "/* identical to box height, or 21px */\n"
                                         "\n"
                                         "/* typo/primary */\n"
                                         "\n"
                                         "color: #002033;")
        self.expType_label.setObjectName("expType_label")
        self.verticalLayout_3.addWidget(self.expType_label)
        self.expType_comboBox = QtWidgets.QComboBox(self.widget_5)
        self.expType_comboBox.setMinimumSize(QtCore.QSize(0, 40))
        self.expType_comboBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.expType_comboBox.setStyleSheet("\n"
                                            "\n"
                                            "#expType_comboBox{\n"
                                            "height: 40px;\n"
                                            "/* control-default/bg */\n"
                                            "font-family: \'Segoe UI\';\n"
                                            "font-weight: 400;\n"
                                            "font-style: normal;\n"
                                            "font-size: 16px;\n"
                                            "\n"
                                            "padding-left: 13px;\n"
                                            "/* control-default/bg-border */\n"
                                            "\n"
                                            "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                            "border-radius: 4px;\n"
                                            "\n"
                                            "color: rgba(0, 32, 51, 0.35);\n"
                                            "outline: 0px;\n"
                                            "}\n"
                                            "\n"
                                            "#expType_comboBox::down-arrow {\n"
                                            "image: url(:/imgs/arrowComboBox.png);\n"
                                            "width: 40px;\n"
                                            "}\n"
                                            "\n"
                                            "#expType_comboBox::drop-down{\n"
                                            "border: 0px;\n"
                                            "width: 40px;\n"
                                            "}\n"
                                            "\n"
                                            "\n"
                                            "\n"
                                            "\n"
                                            "#expType_comboBox::on {\n"
                                            "border: 1px solid #0091FF;\n"
                                            "outline: 0px;\n"
                                            "}\n"
                                            "\n"
                                            "#expType_comboBox QListView {\n"
                                            "outline-color: #fff;\n"
                                            "background-color: #fff;\n"
                                            "\n"
                                            "font-family: \'Segoe UI\';\n"
                                            "font-weight: 400;\n"
                                            "font-style: normal;\n"
                                            "font-size: 16px;\n"
                                            "\n"
                                            "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                            "\n"
                                            "border-radius: 4px;\n"
                                            "margin-top: 7px;\n"
                                            "outline: 0px;\n"
                                            "\n"
                                            "selection-background-color: rgba(0, 32, 51, 0.05);\n"
                                            "selection-color: black;\n"
                                            "padding-top:10px;\n"
                                            "padding-bottom:10px;\n"
                                            "padding-left:12px;\n"
                                            "padding-right:12px;\n"
                                            "}\n"
                                            "\n"
                                            "#expType_comboBox QAbstractItemView::text {\n"
                                            "\n"
                                            "padding: 10px;\n"
                                            "}\n"
                                            "\n"
                                            "\n"
                                            "\n"
                                            "\n"
                                            "")
        self.expType_comboBox.setIconSize(QtCore.QSize(24, 24))
        self.expType_comboBox.setObjectName("expType_comboBox")
        self.expType_comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.expType_comboBox)
        self.gridLayout_2.addWidget(self.widget_5, 1, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.widget_2)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pos_label_2 = QtWidgets.QLabel(self.widget_7)
        self.pos_label_2.setStyleSheet("width: 152px;\n"
                                       "height: 21px;\n"
                                       "\n"
                                       "/* S */\n"
                                       "\n"
                                       "font-family: \'Inter\';\n"
                                       "font-style: normal;\n"
                                       "font-weight: 400;\n"
                                       "font-size: 14px;\n"
                                       "line-height: 150%;\n"
                                       "/* identical to box height, or 21px */\n"
                                       "\n"
                                       "/* typo/primary */\n"
                                       "\n"
                                       "color: #002033;")
        self.pos_label_2.setObjectName("pos_label_2")
        self.verticalLayout_5.addWidget(self.pos_label_2)
        self.pos_comboBox_2 = QtWidgets.QComboBox(self.widget_7)
        self.pos_comboBox_2.setEnabled(False)
        self.pos_comboBox_2.setStyleSheet("\n"
                                          "\n"
                                          "#pos_comboBox_2{\n"
                                          "height: 40px;\n"
                                          "/* control-default/bg */\n"
                                          "font-family: \'Segoe UI\';\n"
                                          "font-weight: 400;\n"
                                          "font-style: normal;\n"
                                          "font-size: 16px;\n"
                                          "\n"
                                          "padding-left: 13px;\n"
                                          "/* control-default/bg-border */\n"
                                          "\n"
                                          "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                          "border-radius: 4px;\n"
                                          "\n"
                                          "color: rgba(0, 32, 51, 0.35);\n"
                                          "outline: 0px;\n"
                                          "}\n"
                                          "\n"
                                          "#pos_comboBox_2::down-arrow {\n"
                                          "image: url(:/imgs/arrowComboBox.png);\n"
                                          "width: 40px;\n"
                                          "}\n"
                                          "\n"
                                          "#pos_comboBox_2::drop-down{\n"
                                          "border: 0px;\n"
                                          "width: 40px;\n"
                                          "}\n"
                                          "\n"
                                          "\n"
                                          "\n"
                                          "\n"
                                          "#expType_comboBox::on {\n"
                                          "border: 1px solid #0091FF;\n"
                                          "outline: 0px;\n"
                                          "}\n"
                                          "\n"
                                          "#expType_comboBox QListView {\n"
                                          "outline-color: #fff;\n"
                                          "background-color: #fff;\n"
                                          "\n"
                                          "font-family: \'Segoe UI\';\n"
                                          "font-weight: 400;\n"
                                          "font-style: normal;\n"
                                          "font-size: 16px;\n"
                                          "\n"
                                          "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                          "\n"
                                          "border-radius: 4px;\n"
                                          "margin-top: 7px;\n"
                                          "outline: 0px;\n"
                                          "\n"
                                          "selection-background-color: rgba(0, 32, 51, 0.05);\n"
                                          "selection-color: black;\n"
                                          "padding-top:10px;\n"
                                          "padding-bottom:10px;\n"
                                          "padding-left:12px;\n"
                                          "padding-right:12px;\n"
                                          "}\n"
                                          "\n"
                                          "#expType_comboBox QAbstractItemView::text {\n"
                                          "\n"
                                          "padding: 10px;\n"
                                          "}\n"
                                          "\n"
                                          "\n"
                                          "\n"
                                          "\n"
                                          "")
        self.pos_comboBox_2.setObjectName("pos_comboBox_2")
        self.pos_comboBox_2.addItem("")
        self.verticalLayout_5.addWidget(self.pos_comboBox_2)
        self.gridLayout_2.addWidget(self.widget_7, 5, 0, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.widget_2)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.repeatSampleNum_label_2 = QtWidgets.QLabel(self.widget_8)
        self.repeatSampleNum_label_2.setStyleSheet("width: 152px;\n"
                                                   "height: 21px;\n"
                                                   "\n"
                                                   "/* S */\n"
                                                   "\n"
                                                   "font-family: \'Inter\';\n"
                                                   "font-style: normal;\n"
                                                   "font-weight: 400;\n"
                                                   "font-size: 14px;\n"
                                                   "line-height: 150%;\n"
                                                   "/* identical to box height, or 21px */\n"
                                                   "\n"
                                                   "/* typo/primary */\n"
                                                   "\n"
                                                   "color: #002033;")
        self.repeatSampleNum_label_2.setWordWrap(True)
        self.repeatSampleNum_label_2.setObjectName("repeatSampleNum_label_2")
        self.verticalLayout_6.addWidget(self.repeatSampleNum_label_2)
        self.repeatSampleNum_spinBox_2 = QtWidgets.QSpinBox(self.widget_8)
        self.repeatSampleNum_spinBox_2.setEnabled(False)
        self.repeatSampleNum_spinBox_2.setMinimumSize(QtCore.QSize(0, 40))
        self.repeatSampleNum_spinBox_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.repeatSampleNum_spinBox_2.setStyleSheet("QSpinBox\n"
                                                     "{\n"
                                                     "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                                     "border-radius: 4px;\n"
                                                     "height: 40px;\n"
                                                     "\n"
                                                     "padding: 0px 11px;\n"
                                                     "gap: 12px;\n"
                                                     "\n"
                                                     "font-family: \'Segoe UI\';\n"
                                                     "font-style: normal;\n"
                                                     "font-weight: 400;\n"
                                                     "font-size: 16px;\n"
                                                     "line-height: 22px;\n"
                                                     "}\n"
                                                     "\n"
                                                     "\n"
                                                     "QSpinBox::up-button {\n"
                                                     "width:40px;\n"
                                                     "image:url(:/imgs/up-arrow.png);\n"
                                                     "padding-top:4px;\n"
                                                     "}\n"
                                                     "\n"
                                                     "QSpinBox::down-button {\n"
                                                     "image:url(:/imgs/down-arrow.png);\n"
                                                     "width:40px;\n"
                                                     "padding-bottom:4px;\n"
                                                     "}\n"
                                                     "\n"
                                                     "\n"
                                                     "QSpinBox::up-button:pressed {\n"
                                                     "width:40px;\n"
                                                     "image:url(:/imgs/up-arrow.png);\n"
                                                     "padding-top:4px;\n"
                                                     "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                                     "}\n"
                                                     "\n"
                                                     "QSpinBox::down-button:pressed {\n"
                                                     "image:url(:/imgs/down-arrow.png);\n"
                                                     "width:40px;\n"
                                                     "padding-bottom:4px;\n"
                                                     "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                                     "}")
        self.repeatSampleNum_spinBox_2.setProperty("value", 1)
        self.repeatSampleNum_spinBox_2.setObjectName("repeatSampleNum_spinBox_2")
        self.verticalLayout_6.addWidget(self.repeatSampleNum_spinBox_2)
        self.gridLayout_2.addWidget(self.widget_8, 4, 1, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.widget_2)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.razbav_label_2 = QtWidgets.QLabel(self.widget_9)
        self.razbav_label_2.setStyleSheet("width: 152px;\n"
                                          "height: 21px;\n"
                                          "\n"
                                          "/* S */\n"
                                          "\n"
                                          "font-family: \'Inter\';\n"
                                          "font-style: normal;\n"
                                          "font-weight: 400;\n"
                                          "font-size: 14px;\n"
                                          "line-height: 150%;\n"
                                          "/* identical to box height, or 21px */\n"
                                          "\n"
                                          "/* typo/primary */\n"
                                          "\n"
                                          "color: #002033;")
        self.razbav_label_2.setObjectName("razbav_label_2")
        self.verticalLayout_7.addWidget(self.razbav_label_2)
        self.razbav_lineEdit_2 = QtWidgets.QLineEdit(self.widget_9)
        self.razbav_lineEdit_2.setEnabled(False)
        self.razbav_lineEdit_2.setMinimumSize(QtCore.QSize(0, 40))
        self.razbav_lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.razbav_lineEdit_2.setStyleSheet("padding: 0px 11px;\n"
                                             "gap: 12px;\n"
                                             "\n"
                                             "position: absolute;\n"
                                             "height: 40px;\n"
                                             "left: 0px;\n"
                                             "right: 0px;\n"
                                             "top: 0px;\n"
                                             "\n"
                                             "/* control-default/bg */\n"
                                             "\n"
                                             "background: #FFFFFF;\n"
                                             "/* control-default/bg-border */\n"
                                             "\n"
                                             "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                             "border-radius: 4px;\n"
                                             "\n"
                                             "\n"
                                             "font-family: \'Segoe UI\';\n"
                                             "font-style: normal;\n"
                                             "font-weight: 400;\n"
                                             "font-size: 16px;\n"
                                             "line-height: 150%;")
        self.razbav_lineEdit_2.setObjectName("razbav_lineEdit_2")
        self.verticalLayout_7.addWidget(self.razbav_lineEdit_2)
        self.gridLayout_2.addWidget(self.widget_9, 6, 0, 1, 1)
        self.widget_10 = QtWidgets.QWidget(self.widget_2)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.plotn_label_2 = QtWidgets.QLabel(self.widget_10)
        self.plotn_label_2.setEnabled(True)
        self.plotn_label_2.setStyleSheet("width: 152px;\n"
                                         "height: 21px;\n"
                                         "\n"
                                         "/* S */\n"
                                         "\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 14px;\n"
                                         "line-height: 150%;\n"
                                         "/* identical to box height, or 21px */\n"
                                         "\n"
                                         "/* typo/primary */\n"
                                         "\n"
                                         "color: #002033;")
        self.plotn_label_2.setObjectName("plotn_label_2")
        self.verticalLayout_8.addWidget(self.plotn_label_2)
        self.plotn_lineEdit_2 = QtWidgets.QLineEdit(self.widget_10)
        self.plotn_lineEdit_2.setEnabled(False)
        self.plotn_lineEdit_2.setMinimumSize(QtCore.QSize(0, 40))
        self.plotn_lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.plotn_lineEdit_2.setStyleSheet("padding: 0px 11px;\n"
                                            "gap: 12px;\n"
                                            "\n"
                                            "position: absolute;\n"
                                            "height: 40px;\n"
                                            "left: 0px;\n"
                                            "right: 0px;\n"
                                            "top: 0px;\n"
                                            "\n"
                                            "/* control-default/bg */\n"
                                            "\n"
                                            "background: #FFFFFF;\n"
                                            "/* control-default/bg-border */\n"
                                            "\n"
                                            "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                            "border-radius: 4px;\n"
                                            "\n"
                                            "\n"
                                            "font-family: \'Segoe UI\';\n"
                                            "font-style: normal;\n"
                                            "font-weight: 400;\n"
                                            "font-size: 16px;\n"
                                            "line-height: 150%;")
        self.plotn_lineEdit_2.setObjectName("plotn_lineEdit_2")
        self.verticalLayout_8.addWidget(self.plotn_lineEdit_2)
        self.gridLayout_2.addWidget(self.widget_10, 6, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.pos_spinBox_2 = QtWidgets.QSpinBox(self.widget_2)
        self.pos_spinBox_2.setEnabled(False)
        self.pos_spinBox_2.setStyleSheet("QSpinBox\n"
                                         "{\n"
                                         "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                         "border-radius: 4px;\n"
                                         "height: 40px;\n"
                                         "\n"
                                         "padding: 0px 11px;\n"
                                         "gap: 12px;\n"
                                         "\n"
                                         "font-family: \'Segoe UI\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 16px;\n"
                                         "line-height: 22px;\n"
                                         "margin-top: 25px;\n"
                                         "}\n"
                                         "\n"
                                         "\n"
                                         "QSpinBox::up-button {\n"
                                         "width:40px;\n"
                                         "image:url(:/imgs/up-arrow.png);\n"
                                         "padding-top:4px;\n"
                                         "}\n"
                                         "\n"
                                         "QSpinBox::down-button {\n"
                                         "image:url(:/imgs/down-arrow.png);\n"
                                         "width:40px;\n"
                                         "padding-bottom:4px;\n"
                                         "}\n"
                                         "\n"
                                         "\n"
                                         "QSpinBox::up-button:pressed {\n"
                                         "width:40px;\n"
                                         "image:url(:/imgs/up-arrow.png);\n"
                                         "padding-top:4px;\n"
                                         "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                         "}\n"
                                         "\n"
                                         "QSpinBox::down-button:pressed {\n"
                                         "image:url(:/imgs/down-arrow.png);\n"
                                         "width:40px;\n"
                                         "padding-bottom:4px;\n"
                                         "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                         "}")
        self.pos_spinBox_2.setProperty("value", 1)
        self.pos_spinBox_2.setObjectName("pos_spinBox_2")
        self.gridLayout_2.addWidget(self.pos_spinBox_2, 5, 1, 1, 1)
        self.autosampler_rButton = QtWidgets.QRadioButton(self.widget_2)
        self.autosampler_rButton.setStyleSheet("QRadioButton{\n"
                                               "font-family: \'Segoe UI\';\n"
                                               "font-style: normal;\n"
                                               "font-weight: 400;\n"
                                               "font-size: 16px;\n"
                                               "line-height: 120%;\n"
                                               "/* or 19px */\n"
                                               "\n"
                                               "spacing: 12px;\n"
                                               "/* control-default/typo */\n"
                                               "\n"
                                               "color: #002033;\n"
                                               "}\n"
                                               "\n"
                                               "QRadioButton::indicator{\n"
                                               "width: 16px;\n"
                                               "height: 16px;\n"
                                               "}\n"
                                               "")
        self.autosampler_rButton.setObjectName("autosampler_rButton")
        self.gridLayout_2.addWidget(self.autosampler_rButton, 3, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.widget_2)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setMinimumSize(QtCore.QSize(1, 0))
        self.line.setMaximumSize(QtCore.QSize(1, 16777215))
        self.line.setStyleSheet("background-color:rgba(0, 32, 51, 0.3);\n"
                                "width: 1px;")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_11 = QtWidgets.QWidget(self.widget_3)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.sampleName_label_2 = QtWidgets.QLabel(self.widget_11)
        self.sampleName_label_2.setStyleSheet("width: 152px;\n"
                                              "height: 21px;\n"
                                              "\n"
                                              "/* S */\n"
                                              "\n"
                                              "font-family: \'Inter\';\n"
                                              "font-style: normal;\n"
                                              "font-weight: 400;\n"
                                              "font-size: 14px;\n"
                                              "line-height: 150%;\n"
                                              "/* identical to box height, or 21px */\n"
                                              "\n"
                                              "/* typo/primary */\n"
                                              "\n"
                                              "color: #002033;")
        self.sampleName_label_2.setObjectName("sampleName_label_2")
        self.verticalLayout_10.addWidget(self.sampleName_label_2)
        self.sampleName_lineEdit_2 = QtWidgets.QLineEdit(self.widget_11)
        self.sampleName_lineEdit_2.setMinimumSize(QtCore.QSize(0, 40))
        self.sampleName_lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.sampleName_lineEdit_2.setStyleSheet("padding: 0px 11px;\n"
                                                 "gap: 12px;\n"
                                                 "\n"
                                                 "position: absolute;\n"
                                                 "height: 40px;\n"
                                                 "left: 0px;\n"
                                                 "right: 0px;\n"
                                                 "top: 0px;\n"
                                                 "\n"
                                                 "/* control-default/bg */\n"
                                                 "\n"
                                                 "background: #FFFFFF;\n"
                                                 "/* control-default/bg-border */\n"
                                                 "\n"
                                                 "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                                 "border-radius: 4px;\n"
                                                 "\n"
                                                 "\n"
                                                 "font-family: \'Segoe UI\';\n"
                                                 "font-style: normal;\n"
                                                 "font-weight: 400;\n"
                                                 "font-size: 16px;\n"
                                                 "line-height: 150%;")
        self.sampleName_lineEdit_2.setObjectName("sampleName_lineEdit_2")
        self.verticalLayout_10.addWidget(self.sampleName_lineEdit_2)
        self.verticalLayout_9.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.widget_3)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.value_label_2 = QtWidgets.QLabel(self.widget_12)
        self.value_label_2.setStyleSheet("width: 152px;\n"
                                         "height: 21px;\n"
                                         "\n"
                                         "/* S */\n"
                                         "\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 14px;\n"
                                         "line-height: 150%;\n"
                                         "/* identical to box height, or 21px */\n"
                                         "\n"
                                         "/* typo/primary */\n"
                                         "\n"
                                         "color: #002033;")
        self.value_label_2.setObjectName("value_label_2")
        self.verticalLayout_11.addWidget(self.value_label_2)
        self.value_lineEdit_2 = QtWidgets.QLineEdit(self.widget_12)
        self.value_lineEdit_2.setMinimumSize(QtCore.QSize(0, 40))
        self.value_lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.value_lineEdit_2.setStyleSheet("padding: 0px 11px;\n"
                                            "gap: 12px;\n"
                                            "\n"
                                            "position: absolute;\n"
                                            "height: 40px;\n"
                                            "left: 0px;\n"
                                            "right: 0px;\n"
                                            "top: 0px;\n"
                                            "\n"
                                            "/* control-default/bg */\n"
                                            "\n"
                                            "background: #FFFFFF;\n"
                                            "/* control-default/bg-border */\n"
                                            "\n"
                                            "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                            "border-radius: 4px;\n"
                                            "\n"
                                            "\n"
                                            "font-family: \'Segoe UI\';\n"
                                            "font-style: normal;\n"
                                            "font-weight: 400;\n"
                                            "font-size: 16px;\n"
                                            "line-height: 150%;")
        self.value_lineEdit_2.setObjectName("value_lineEdit_2")
        self.verticalLayout_11.addWidget(self.value_lineEdit_2)
        self.verticalLayout_9.addWidget(self.widget_12)
        self.widget_13 = QtWidgets.QWidget(self.widget_3)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(8)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.razmConcentr_label_2 = QtWidgets.QLabel(self.widget_13)
        self.razmConcentr_label_2.setStyleSheet("width: 152px;\n"
                                                "height: 21px;\n"
                                                "\n"
                                                "/* S */\n"
                                                "\n"
                                                "font-family: \'Inter\';\n"
                                                "font-style: normal;\n"
                                                "font-weight: 400;\n"
                                                "font-size: 14px;\n"
                                                "line-height: 150%;\n"
                                                "/* identical to box height, or 21px */\n"
                                                "\n"
                                                "/* typo/primary */\n"
                                                "\n"
                                                "color: #002033;")
        self.razmConcentr_label_2.setWordWrap(True)
        self.razmConcentr_label_2.setObjectName("razmConcentr_label_2")
        self.verticalLayout_12.addWidget(self.razmConcentr_label_2)
        self.razmConcentr_comboBox_2 = QtWidgets.QComboBox(self.widget_13)
        self.razmConcentr_comboBox_2.setStyleSheet("\n"
                                                   "\n"
                                                   "#razmConcentr_comboBox_2{\n"
                                                   "height: 40px;\n"
                                                   "/* control-default/bg */\n"
                                                   "font-family: \'Segoe UI\';\n"
                                                   "font-weight: 400;\n"
                                                   "font-style: normal;\n"
                                                   "font-size: 16px;\n"
                                                   "\n"
                                                   "padding-left: 13px;\n"
                                                   "/* control-default/bg-border */\n"
                                                   "\n"
                                                   "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                                   "border-radius: 4px;\n"
                                                   "\n"
                                                   "color: rgba(0, 32, 51, 0.35);\n"
                                                   "outline: 0px;\n"
                                                   "}\n"
                                                   "\n"
                                                   "#razmConcentr_comboBox_2::down-arrow {\n"
                                                   "image: url(:/imgs/arrowComboBox.png);\n"
                                                   "width: 40px;\n"
                                                   "}\n"
                                                   "\n"
                                                   "#razmConcentr_comboBox_2::drop-down{\n"
                                                   "border: 0px;\n"
                                                   "width: 40px;\n"
                                                   "}\n"
                                                   "\n"
                                                   "\n"
                                                   "\n"
                                                   "\n"
                                                   "#razmConcentr_comboBox_2::on {\n"
                                                   "border: 1px solid #0091FF;\n"
                                                   "outline: 0px;\n"
                                                   "}\n"
                                                   "\n"
                                                   "#razmConcentr_comboBox_2 QListView {\n"
                                                   "outline-color: #fff;\n"
                                                   "background-color: #fff;\n"
                                                   "\n"
                                                   "font-family: \'Segoe UI\';\n"
                                                   "font-weight: 400;\n"
                                                   "font-style: normal;\n"
                                                   "font-size: 16px;\n"
                                                   "\n"
                                                   "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                                   "\n"
                                                   "border-radius: 4px;\n"
                                                   "margin-top: 7px;\n"
                                                   "outline: 0px;\n"
                                                   "\n"
                                                   "selection-background-color: rgba(0, 32, 51, 0.05);\n"
                                                   "selection-color: black;\n"
                                                   "padding-top:10px;\n"
                                                   "padding-bottom:10px;\n"
                                                   "padding-left:12px;\n"
                                                   "padding-right:12px;\n"
                                                   "}\n"
                                                   "\n"
                                                   "#razmConcentr_comboBox_2 QAbstractItemView::text {\n"
                                                   "\n"
                                                   "padding: 10px;\n"
                                                   "}\n"
                                                   "\n"
                                                   "\n"
                                                   "\n"
                                                   "\n"
                                                   "")
        self.razmConcentr_comboBox_2.setObjectName("razmConcentr_comboBox_2")
        self.razmConcentr_comboBox_2.addItem("")
        self.verticalLayout_12.addWidget(self.razmConcentr_comboBox_2)
        self.verticalLayout_9.addWidget(self.widget_13)
        self.widget_14 = QtWidgets.QWidget(self.widget_3)
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(8)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.operator_label_2 = QtWidgets.QLabel(self.widget_14)
        self.operator_label_2.setStyleSheet("width: 152px;\n"
                                            "height: 21px;\n"
                                            "\n"
                                            "/* S */\n"
                                            "\n"
                                            "font-family: \'Inter\';\n"
                                            "font-style: normal;\n"
                                            "font-weight: 400;\n"
                                            "font-size: 14px;\n"
                                            "line-height: 150%;\n"
                                            "/* identical to box height, or 21px */\n"
                                            "\n"
                                            "/* typo/primary */\n"
                                            "\n"
                                            "color: #002033;")
        self.operator_label_2.setObjectName("operator_label_2")
        self.verticalLayout_13.addWidget(self.operator_label_2)
        self.operator_lineEdit_2 = QtWidgets.QLineEdit(self.widget_14)
        self.operator_lineEdit_2.setStyleSheet("padding: 0px 11px;\n"
                                               "gap: 12px;\n"
                                               "\n"
                                               "position: absolute;\n"
                                               "height: 40px;\n"
                                               "left: 0px;\n"
                                               "right: 0px;\n"
                                               "top: 0px;\n"
                                               "\n"
                                               "/* control-default/bg */\n"
                                               "\n"
                                               "background: #FFFFFF;\n"
                                               "/* control-default/bg-border */\n"
                                               "\n"
                                               "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                               "border-radius: 4px;\n"
                                               "\n"
                                               "\n"
                                               "font-family: \'Segoe UI\';\n"
                                               "font-style: normal;\n"
                                               "font-weight: 400;\n"
                                               "font-size: 16px;\n"
                                               "line-height: 150%;")
        self.operator_lineEdit_2.setObjectName("operator_lineEdit_2")
        self.verticalLayout_13.addWidget(self.operator_lineEdit_2)
        self.verticalLayout_9.addWidget(self.widget_14)
        self.widget_15 = QtWidgets.QWidget(self.widget_3)
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(8)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.comment_label_2 = QtWidgets.QLabel(self.widget_15)
        self.comment_label_2.setStyleSheet("width: 152px;\n"
                                           "height: 21px;\n"
                                           "\n"
                                           "/* S */\n"
                                           "\n"
                                           "font-family: \'Inter\';\n"
                                           "font-style: normal;\n"
                                           "font-weight: 400;\n"
                                           "font-size: 14px;\n"
                                           "line-height: 150%;\n"
                                           "/* identical to box height, or 21px */\n"
                                           "\n"
                                           "/* typo/primary */\n"
                                           "\n"
                                           "color: #002033;")
        self.comment_label_2.setObjectName("comment_label_2")
        self.verticalLayout_14.addWidget(self.comment_label_2)
        self.comment_plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.widget_15)
        self.comment_plainTextEdit_2.setStyleSheet("padding: 0px 11px;\n"
                                                   "gap: 12px;\n"
                                                   "\n"
                                                   "position: absolute;\n"
                                                   "height: 40px;\n"
                                                   "left: 0px;\n"
                                                   "right: 0px;\n"
                                                   "top: 0px;\n"
                                                   "\n"
                                                   "/* control-default/bg */\n"
                                                   "\n"
                                                   "background: #FFFFFF;\n"
                                                   "/* control-default/bg-border */\n"
                                                   "\n"
                                                   "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                                   "border-radius: 4px;\n"
                                                   "\n"
                                                   "\n"
                                                   "font-family: \'Segoe UI\';\n"
                                                   "font-style: normal;\n"
                                                   "font-weight: 400;\n"
                                                   "font-size: 16px;\n"
                                                   "line-height: 150%;")
        self.comment_plainTextEdit_2.setObjectName("comment_plainTextEdit_2")
        self.verticalLayout_14.addWidget(self.comment_plainTextEdit_2)
        self.verticalLayout_9.addWidget(self.widget_15)
        self.horizontalLayout_5.addWidget(self.widget_3)
        self.verticalLayout.addWidget(self.widget)
        self.frame = QtWidgets.QFrame(creSampWindow)
        self.frame.setMinimumSize(QtCore.QSize(1142, 33))
        self.frame.setMaximumSize(QtCore.QSize(1142, 33))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(12)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.cancelSampButton = QtWidgets.QPushButton(self.frame)
        self.cancelSampButton.setMinimumSize(QtCore.QSize(0, 32))
        self.cancelSampButton.setMaximumSize(QtCore.QSize(16777215, 32))
        self.cancelSampButton.setStyleSheet("#cancelSampButton{\n"
                                            "\n"
                                            "height: 32px;\n"
                                            "width: 81px;\n"
                                            "/* control-primary/bg */\n"
                                            "\n"
                                            "\n"
                                            "background: #fff;\n"
                                            "border-radius: 16px;\n"
                                            "border: 1px solid #0078D2;\n"
                                            "\n"
                                            "\n"
                                            "font-family: \'Segoe UI\';\n"
                                            "font-style: normal;\n"
                                            "font-weight: 400;\n"
                                            "font-size: 16px;\n"
                                            "line-height: 40px;\n"
                                            "\n"
                                            "\n"
                                            "/* control-primary/typo */\n"
                                            "\n"
                                            "color: #0078D2;\n"
                                            "}\n"
                                            "\n"
                                            "#cancelSampButton::hover{\n"
                                            "background: rgb(205, 238, 255);\n"
                                            "\n"
                                            "}\n"
                                            "\n"
                                            "#cancelSampButton::pressed{\n"
                                            "\n"
                                            "border: 4px solid rgb(139, 205, 255);\n"
                                            "}")
        self.cancelSampButton.setObjectName("cancelSampButton")
        self.horizontalLayout_4.addWidget(self.cancelSampButton)
        self.addSampButton = QtWidgets.QPushButton(self.frame)
        self.addSampButton.setMinimumSize(QtCore.QSize(94, 32))
        self.addSampButton.setMaximumSize(QtCore.QSize(94, 32))
        self.addSampButton.setStyleSheet("#addSampButton{\n"
                                         "\n"
                                         "\n"
                                         "/* control-primary/bg */\n"
                                         "\n"
                                         "\n"
                                         "background: #0078D2;\n"
                                         "border-radius: 16px;\n"
                                         "\n"
                                         "\n"
                                         "font-family: \'Segoe UI\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 16px;\n"
                                         "line-height: 40px;\n"
                                         "\n"
                                         "\n"
                                         "/* control-primary/typo */\n"
                                         "\n"
                                         "color: #FFFFFF;\n"
                                         "}\n"
                                         "\n"
                                         "#addSampButton::hover{\n"
                                         "background: rgb(0, 134, 229);\n"
                                         "\n"
                                         "}\n"
                                         "\n"
                                         "#addSampButton::pressed{\n"
                                         "\n"
                                         "border: 4px solid rgb(0, 101, 173);\n"
                                         "}")
        self.addSampButton.setObjectName("addSampButton")
        self.horizontalLayout_4.addWidget(self.addSampButton)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(creSampWindow)
        QtCore.QMetaObject.connectSlotsByName(creSampWindow)

    def retranslateUi(self, creSampWindow):
        _translate = QtCore.QCoreApplication.translate
        creSampWindow.setWindowTitle(_translate("creSampWindow", "Создание группы образцов"))
        self.label.setText(_translate("creSampWindow", "Создание группы образцов"))
        self.groupName_label.setText(_translate("creSampWindow", "Имя группы образцов"))
        self.groupName_lineEdit.setText(_translate("creSampWindow", "Группа 1"))
        self.sampleNum_label.setText(_translate("creSampWindow", "Число образцов"))
        self.expType_label.setText(_translate("creSampWindow", "Тип экспермента"))
        self.expType_comboBox.setItemText(0, _translate("creSampWindow", "По умолчанию"))
        self.pos_label_2.setText(_translate("creSampWindow", "Первая позиция"))
        self.pos_comboBox_2.setItemText(0, _translate("creSampWindow", "Tray 1"))
        self.repeatSampleNum_label_2.setText(_translate("creSampWindow", "Количество повторов образцов"))
        self.razbav_label_2.setText(_translate("creSampWindow", "Разбавление"))
        self.razbav_lineEdit_2.setText(_translate("creSampWindow", "1"))
        self.plotn_label_2.setText(_translate("creSampWindow", "Плотность"))
        self.plotn_lineEdit_2.setText(_translate("creSampWindow", "1"))
        self.autosampler_rButton.setText(_translate("creSampWindow", "Автосемплер"))
        self.sampleName_label_2.setText(_translate("creSampWindow", "Имя пробы: "))
        self.sampleName_lineEdit_2.setText(_translate("creSampWindow", "Проба 1"))
        self.value_label_2.setText(_translate("creSampWindow", "Количество:"))
        self.value_lineEdit_2.setText(_translate("creSampWindow", "1"))
        self.razmConcentr_label_2.setText(_translate("creSampWindow", "Размерность концентрации:"))
        self.razmConcentr_comboBox_2.setItemText(0, _translate("creSampWindow", "ммоль/л"))
        self.operator_label_2.setText(_translate("creSampWindow", "Оператор:"))
        self.operator_lineEdit_2.setText(_translate("creSampWindow", "Оператор 1"))
        self.comment_label_2.setText(_translate("creSampWindow", "Комментарий:"))
        self.comment_plainTextEdit_2.setPlainText(_translate("creSampWindow", "Комментарий 1"))
        self.cancelSampButton.setText(_translate("creSampWindow", "Отмена"))
        self.addSampButton.setText(_translate("creSampWindow", "Добавить"))


import resources

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    creSampWindow = QtWidgets.QDialog()
    ui = Ui_creSampWindow()
    ui.setupUi(creSampWindow)
    creSampWindow.show()
    sys.exit(app.exec_())
