# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'workWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WorkWindow(object):
    def setupUi(self, WorkWindow):
        WorkWindow.setObjectName("WorkWindow")
        WorkWindow.setEnabled(True)
        WorkWindow.resize(1440, 838)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WorkWindow.sizePolicy().hasHeightForWidth())
        WorkWindow.setSizePolicy(sizePolicy)
        WorkWindow.setMinimumSize(QtCore.QSize(1440, 838))
        WorkWindow.setMaximumSize(QtCore.QSize(1440, 838))
        WorkWindow.setStyleSheet("background-color:#FFFFFF;")
        self.centralwidget = QtWidgets.QWidget(WorkWindow)
        self.centralwidget.setStyleSheet("color:FFFFFF\n"
                                         "")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(24, 92, 1385, 691))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setStyleSheet("#tabWidget {\n"
                                     "\n"
                                     "background: white;\n"
                                     "outline: 0px;\n"
                                     "}\n"
                                     "#tabWidget:pane {\n"
                                     "border: 0px;\n"
                                     "}\n"
                                     "\n"
                                     "#tabWidget:tab-bar {\n"
                                     "    alignment: left;\n"
                                     "}\n"
                                     "\n"
                                     "#tabWidget QTabBar{\n"
                                     "font-family: \'Segoe UI\';\n"
                                     "font-style: normal;\n"
                                     "font-weight: 400;\n"
                                     "font-size: 18px;\n"
                                     "color: rgba(0, 57, 92, 0.8);\n"
                                     "\n"
                                     "}\n"
                                     "\n"
                                     "#tabWidget QTabBar::tab{\n"
                                     "margin:4px;\n"
                                     "padding:8px;\n"
                                     "border-bottom: 2px solid rgba(0, 66, 105, 0.07);\n"
                                     "background-color: #fff;\n"
                                     "border-radius: 1px;\n"
                                     "}\n"
                                     "\n"
                                     "#tabWidget QTabBar::tab::selected{\n"
                                     "\n"
                                     "\n"
                                     "border-bottom: 2px solid #0078D2;\n"
                                     "background-color: #fff;\n"
                                     "\n"
                                     "border-radius: 1px;\n"
                                     "color: #0078D2;\n"
                                     "}\n"
                                     "\n"
                                     "#tabWidget QTabBar::tab::hover{\n"
                                     "\n"
                                     "\n"
                                     "border-bottom: 2px solid rgb(33, 170, 255);\n"
                                     "background-color: #fff;\n"
                                     "\n"
                                     "border-radius: 1px;\n"
                                     "color: rgb(33, 170, 255);\n"
                                     "}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("")
        self.tab.setObjectName("tab")
        self.statusHeader_label = QtWidgets.QLabel(self.tab)
        self.statusHeader_label.setGeometry(QtCore.QRect(22, 40, 178, 25))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.statusHeader_label.setFont(font)
        self.statusHeader_label.setStyleSheet("width: 175px;\n"
                                              "height: 30px;\n"
                                              "\n"
                                              "/* XL */\n"
                                              "\n"
                                              "font-family: \'Inter\';\n"
                                              "font-style: normal;\n"
                                              "font-weight: 400;\n"
                                              "font-size: 20px;\n"
                                              "line-height: 150%;\n"
                                              "\n"
                                              "color: #002033;")
        self.statusHeader_label.setObjectName("statusHeader_label")
        self.graph_label = QtWidgets.QLabel(self.tab)
        self.graph_label.setGeometry(QtCore.QRect(405, 15, 971, 601))
        self.graph_label.setAutoFillBackground(False)
        self.graph_label.setStyleSheet("\n"
                                       "border-left: 1px solid #ECF1F4;")
        self.graph_label.setLineWidth(1)
        self.graph_label.setText("")
        self.graph_label.setObjectName("graph_label")
        self.MplWidget = MplWidget(self.tab)
        self.MplWidget.setGeometry(QtCore.QRect(410, 30, 971, 591))
        self.MplWidget.setObjectName("MplWidget")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(46, 94, 333, 351))
        self.widget.setStyleSheet("font-family: \'Inter\';\n"
                                  "font-style: normal;\n"
                                  "font-weight: 400;\n"
                                  "font-size: 16px;\n"
                                  "line-height: 150%;\n"
                                  "/* bg/tone */\n"
                                  "\n"
                                  "color: rgba(0, 32, 51, 0.85);")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(12, 16, 12, 11)
        self.gridLayout_2.setHorizontalSpacing(16)
        self.gridLayout_2.setVerticalSpacing(32)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Controller_label = QtWidgets.QLabel(self.widget)
        self.Controller_label.setStyleSheet("")
        self.Controller_label.setWordWrap(True)
        self.Controller_label.setObjectName("Controller_label")
        self.gridLayout_2.addWidget(self.Controller_label, 0, 1, 1, 1)
        self.cellTemp_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cellTemp_label.setFont(font)
        self.cellTemp_label.setWordWrap(True)
        self.cellTemp_label.setObjectName("cellTemp_label")
        self.gridLayout_2.addWidget(self.cellTemp_label, 3, 1, 1, 1)
        self.outerTemp_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.outerTemp_label.setFont(font)
        self.outerTemp_label.setWordWrap(True)
        self.outerTemp_label.setObjectName("outerTemp_label")
        self.gridLayout_2.addWidget(self.outerTemp_label, 1, 1, 1, 1)
        self.innerTemp_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.innerTemp_label.setFont(font)
        self.innerTemp_label.setWordWrap(True)
        self.innerTemp_label.setObjectName("innerTemp_label")
        self.gridLayout_2.addWidget(self.innerTemp_label, 2, 1, 1, 1)
        self.sampler_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sampler_label.setFont(font)
        self.sampler_label.setWordWrap(True)
        self.sampler_label.setObjectName("sampler_label")
        self.gridLayout_2.addWidget(self.sampler_label, 4, 1, 1, 1)
        self.CLMeter_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.CLMeter_label.setFont(font)
        self.CLMeter_label.setToolTipDuration(-2)
        self.CLMeter_label.setWordWrap(True)
        self.CLMeter_label.setObjectName("CLMeter_label")
        self.gridLayout_2.addWidget(self.CLMeter_label, 5, 1, 1, 1)
        self.ControllerIndicator_label = QtWidgets.QLabel(self.widget)
        self.ControllerIndicator_label.setMinimumSize(QtCore.QSize(15, 15))
        self.ControllerIndicator_label.setMaximumSize(QtCore.QSize(15, 15))
        self.ControllerIndicator_label.setStyleSheet("#ControllerIndicator_label {\n"
                                                     "background-color:#EB5757;\n"
                                                     "border-radius: 5px;\n"
                                                     "\n"
                                                     "}\n"
                                                     "\n"
                                                     "QToolTip {\n"
                                                     "\n"
                                                     "/* bg/default\n"
                                                     "\n"
                                                     "Основной цвет фона\n"
                                                     "*/\n"
                                                     "\n"
                                                     "opacity: 90;\n"
                                                     "border: 8px solid black;\n"
                                                     "\n"
                                                     "font-family: \'Segoe UI\';\n"
                                                     "font-style: normal;\n"
                                                     "font-weight: 400;\n"
                                                     "font-size: 12px;\n"
                                                     "line-height: 120%;\n"
                                                     "color: #002033;\n"
                                                     "min-width: 233px;\n"
                                                     "min-height: 49px;\n"
                                                     "text-align:center;\n"
                                                     "padding:15px;\n"
                                                     "\n"
                                                     "border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 200, 200, 80), stop:1 rgba(255, 255, 255, 0));\n"
                                                     "border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(200, 200, 200, 80), stop:1 rgba(255, 255, 255, 0));\n"
                                                     "border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(200, 200, 200, 80), stop:1 rgba(255, 255, 255, 0));\n"
                                                     "border-top-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(200, 200, 200, 80), stop:1 rgba(255, 255, 255, 0));\n"
                                                     "\n"
                                                     "}\n"
                                                     "\n"
                                                     "\n"
                                                     "")
        self.ControllerIndicator_label.setText("")
        self.ControllerIndicator_label.setObjectName("ControllerIndicator_label")
        self.gridLayout_2.addWidget(self.ControllerIndicator_label, 0, 2, 1, 1)
        self.outerTempIndicator_label = QtWidgets.QLabel(self.widget)
        self.outerTempIndicator_label.setMinimumSize(QtCore.QSize(15, 15))
        self.outerTempIndicator_label.setMaximumSize(QtCore.QSize(14, 14))
        self.outerTempIndicator_label.setStyleSheet("\n"
                                                    "background-color:#EB5757;\n"
                                                    "border-radius: 5px;")
        self.outerTempIndicator_label.setText("")
        self.outerTempIndicator_label.setObjectName("outerTempIndicator_label")
        self.gridLayout_2.addWidget(self.outerTempIndicator_label, 1, 2, 1, 1)
        self.innerTempIndicator_label = QtWidgets.QLabel(self.widget)
        self.innerTempIndicator_label.setMinimumSize(QtCore.QSize(10, 1))
        self.innerTempIndicator_label.setMaximumSize(QtCore.QSize(15, 15))
        self.innerTempIndicator_label.setStyleSheet("\n"
                                                    "background-color:#EB5757;\n"
                                                    "border-radius: 5px;")
        self.innerTempIndicator_label.setText("")
        self.innerTempIndicator_label.setObjectName("innerTempIndicator_label")
        self.gridLayout_2.addWidget(self.innerTempIndicator_label, 2, 2, 1, 1)
        self.cellTempIndicator_label = QtWidgets.QLabel(self.widget)
        self.cellTempIndicator_label.setMinimumSize(QtCore.QSize(15, 15))
        self.cellTempIndicator_label.setMaximumSize(QtCore.QSize(15, 15))
        self.cellTempIndicator_label.setStyleSheet("\n"
                                                   "background-color:#EB5757;\n"
                                                   "border-radius: 5px;")
        self.cellTempIndicator_label.setText("")
        self.cellTempIndicator_label.setObjectName("cellTempIndicator_label")
        self.gridLayout_2.addWidget(self.cellTempIndicator_label, 3, 2, 1, 1)
        self.samplerIndicator_label = QtWidgets.QLabel(self.widget)
        self.samplerIndicator_label.setMinimumSize(QtCore.QSize(15, 15))
        self.samplerIndicator_label.setMaximumSize(QtCore.QSize(15, 15))
        self.samplerIndicator_label.setStyleSheet("\n"
                                                  "background-color:#EB5757;\n"
                                                  "border-radius: 5px;")
        self.samplerIndicator_label.setText("")
        self.samplerIndicator_label.setObjectName("samplerIndicator_label")
        self.gridLayout_2.addWidget(self.samplerIndicator_label, 4, 2, 1, 1)
        self.CLMeterIndicator_label = QtWidgets.QLabel(self.widget)
        self.CLMeterIndicator_label.setMinimumSize(QtCore.QSize(15, 15))
        self.CLMeterIndicator_label.setMaximumSize(QtCore.QSize(15, 15))
        self.CLMeterIndicator_label.setToolTipDuration(-1)
        self.CLMeterIndicator_label.setWhatsThis("")
        self.CLMeterIndicator_label.setStyleSheet("\n"
                                                  "background-color:#EB5757;\n"
                                                  "border-radius: 5px;")
        self.CLMeterIndicator_label.setText("")
        self.CLMeterIndicator_label.setObjectName("CLMeterIndicator_label")
        self.gridLayout_2.addWidget(self.CLMeterIndicator_label, 5, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.devices_label = QtWidgets.QLabel(self.tab_2)
        self.devices_label.setGeometry(QtCore.QRect(0, 40, 103, 25))
        self.devices_label.setStyleSheet("/* Устройства */\n"
                                         "\n"
                                         "\n"
                                         "width: 113px;\n"
                                         "height: 30px;\n"
                                         "\n"
                                         "/* XL */\n"
                                         "\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 20px;\n"
                                         "line-height: 150%;\n"
                                         "\n"
                                         "\n"
                                         "/* bg/shadow */\n"
                                         "\n"
                                         "color: #002033;")
        self.devices_label.setObjectName("devices_label")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 94, 1381, 551))
        self.tabWidget_2.setMinimumSize(QtCore.QSize(1381, 551))
        self.tabWidget_2.setMaximumSize(QtCore.QSize(1381, 551))
        self.tabWidget_2.setStyleSheet("#tabWidget_2 {\n"
                                       "\n"
                                       "background: white;\n"
                                       "outline: 0px;\n"
                                       "}\n"
                                       "#tabWidget_2:pane {\n"
                                       "border: 0px;\n"
                                       "}\n"
                                       "\n"
                                       "#tabWidget_2:tab-bar {\n"
                                       "    alignment: left;\n"
                                       "}\n"
                                       "\n"
                                       "#tabWidget_2 QTabBar{\n"
                                       "font-family: \'Segoe UI\';\n"
                                       "font-style: normal;\n"
                                       "font-weight: 400;\n"
                                       "font-size: 18px;\n"
                                       "color: rgba(0, 57, 92, 0.8);\n"
                                       "\n"
                                       "}\n"
                                       "\n"
                                       "#tabWidget_2 QTabBar::tab{\n"
                                       "margin:4px;\n"
                                       "padding:8px;\n"
                                       "border-right: 2px solid rgba(0, 66, 105, 0.07);\n"
                                       "background-color: #fff;\n"
                                       "border-radius: 1px;\n"
                                       "}\n"
                                       "\n"
                                       "#tabWidget_2 QTabBar::tab::selected{\n"
                                       "\n"
                                       "\n"
                                       "border-right: 2px solid #0078D2;\n"
                                       "background-color: #fff;\n"
                                       "\n"
                                       "border-radius: 1px;\n"
                                       "color: #0078D2;\n"
                                       "}\n"
                                       "\n"
                                       "#tabWidget_2 QTabBar::tab::hover{\n"
                                       "\n"
                                       "\n"
                                       "border-right: 2px solid rgb(33, 170, 255);\n"
                                       "background-color: #fff;\n"
                                       "\n"
                                       "border-radius: 1px;\n"
                                       "color: rgb(33, 170, 255);\n"
                                       "}")
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_2 = QtWidgets.QLabel(self.tab_5)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1300, 540))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(1300, 540))
        self.label_2.setMaximumSize(QtCore.QSize(1300, 540))
        self.label_2.setStyleSheet("image: url(:/imgs/Burner.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_3 = QtWidgets.QLabel(self.tab_6)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1300, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(1300, 500))
        self.label_3.setMaximumSize(QtCore.QSize(1300, 500))
        self.label_3.setSizeIncrement(QtCore.QSize(1300, 450))
        self.label_3.setStyleSheet("image: url(:/imgs/CLMeter.png);\n"
                                   "")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setEnabled(False)
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget.setGeometry(QtCore.QRect(0, 172, 1381, 351))
        self.tableWidget.setMinimumSize(QtCore.QSize(801, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("#tableWidget {\n"
                                       "/* Table */\n"
                                       "\n"
                                       "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                       "box-sizing: border-box;\n"
                                       "\n"
                                       "/* Auto layout */\n"
                                       "\n"
                                       "border-radius: 8px;\n"
                                       "/* control-default/bg-border */\n"
                                       "\n"
                                       "\n"
                                       "\n"
                                       "}\n"
                                       "\n"
                                       "#tableWidget QHeaderView::section:first {\n"
                                       "\n"
                                       "border-top-left-radius: 8px;\n"
                                       "border-left: 1px solid rgba(0, 66, 105, 0.28);\n"
                                       "alignment: left ;\n"
                                       "width: 353px;\n"
                                       "}\n"
                                       "\n"
                                       "#tableWidget QHeaderView::section{\n"
                                       "/* S */\n"
                                       "\n"
                                       "font-family: \'Inter\';\n"
                                       "font-style: normal;\n"
                                       "font-weight: 400;\n"
                                       "font-size: 14px;\n"
                                       "line-height: 150%;\n"
                                       "\n"
                                       "\n"
                                       "color: #002033;\n"
                                       "\n"
                                       "\n"
                                       "height:58px;\n"
                                       "background: #FFFFFF;\n"
                                       "border-left: 0px solid rgba(0, 66, 105, 0.28);\n"
                                       "border-top: 1px solid rgba(0, 66, 105, 0.28);\n"
                                       "border-right: 1px solid rgba(0, 66, 105, 0.28);\n"
                                       "border-bottom: 1px solid rgba(0, 66, 105, 0.28);\n"
                                       "}\n"
                                       "\n"
                                       "#tableWidget QHeaderView::section:last {\n"
                                       "\n"
                                       "border-top-right-radius: 8px;\n"
                                       "\n"
                                       "}\n"
                                       "\n"
                                       "")
        self.tableWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget.setMidLineWidth(0)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setAutoScrollMargin(12)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(10)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.scrollArea = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea.setGeometry(QtCore.QRect(0, 530, 1381, 100))
        self.scrollArea.setStyleSheet("\n"
                                      "\n"
                                      "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                      "border-radius: 8px;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1379, 98))
        self.scrollAreaWidgetContents.setStyleSheet("border: 0px;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.descriptin_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.descriptin_label.setGeometry(QtCore.QRect(0, 10, 1381, 81))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.descriptin_label.setFont(font)
        self.descriptin_label.setStyleSheet("border: 0px;\n"
                                            "border-radius:8px;\n"
                                            "margin-bottom:2px;")
        self.descriptin_label.setText("")
        self.descriptin_label.setScaledContents(False)
        self.descriptin_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.descriptin_label.setWordWrap(True)
        self.descriptin_label.setTextInteractionFlags(
            QtCore.Qt.LinksAccessibleByMouse | QtCore.Qt.TextSelectableByMouse)
        self.descriptin_label.setObjectName("descriptin_label")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.actions_label = QtWidgets.QLabel(self.tab_3)
        self.actions_label.setGeometry(QtCore.QRect(0, 16, 95, 30))
        self.actions_label.setMinimumSize(QtCore.QSize(95, 30))
        self.actions_label.setMaximumSize(QtCore.QSize(95, 30))
        self.actions_label.setStyleSheet("/* Действия */\n"
                                         "\n"
                                         "\n"
                                         "width: 95px;\n"
                                         "height: 30px;\n"
                                         "\n"
                                         "/* XL */\n"
                                         "\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 20px;\n"
                                         "line-height: 150%;\n"
                                         "/* identical to box height, or 30px */\n"
                                         "\n"
                                         "\n"
                                         "\n"
                                         "/* bg/shadow */\n"
                                         "\n"
                                         "color: #002033;")
        self.actions_label.setObjectName("actions_label")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(0, 48, 300, 16))
        self.label.setMinimumSize(QtCore.QSize(300, 0))
        self.label.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label.setStyleSheet("/* Выберете строку чтобы применить действие */\n"
                                 "\n"
                                 "\n"
                                 "width: 268px;\n"
                                 "height: 18px;\n"
                                 "\n"
                                 "/* XS */\n"
                                 "\n"
                                 "font-family: \'Inter\';\n"
                                 "font-style: normal;\n"
                                 "font-weight: 400;\n"
                                 "font-size: 12px;\n"
                                 "line-height: 150%;\n"
                                 "/* identical to box height, or 18px */\n"
                                 "\n"
                                 "/* typo/secondary */\n"
                                 "\n"
                                 "color: rgba(0, 32, 51, 0.6);")
        self.label.setObjectName("label")
        self.controlPanel = QtWidgets.QWidget(self.tab_3)
        self.controlPanel.setGeometry(QtCore.QRect(0, 74, 484, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlPanel.sizePolicy().hasHeightForWidth())
        self.controlPanel.setSizePolicy(sizePolicy)
        self.controlPanel.setMinimumSize(QtCore.QSize(484, 34))
        self.controlPanel.setMaximumSize(QtCore.QSize(484, 34))
        self.controlPanel.setObjectName("controlPanel")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.controlPanel)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.StartBtn = QtWidgets.QPushButton(self.controlPanel)
        self.StartBtn.setMinimumSize(QtCore.QSize(32, 32))
        self.StartBtn.setMaximumSize(QtCore.QSize(32, 32))
        self.StartBtn.setStyleSheet("#StartBtn{\n"
                                    "box-sizing: border-box;\n"
                                    "\n"
                                    "align: top;\n"
                                    "\n"
                                    "/* control-default/bg */\n"
                                    "\n"
                                    "background: #FFFFFF;\n"
                                    "/* control-default/typo-placeholder */\n"
                                    "\n"
                                    "border: 1px solid #09B37B;\n"
                                    "\n"
                                    "border-radius: 4px;\n"
                                    "}\n"
                                    "\n"
                                    "#StartBtn::hover {\n"
                                    "border: 1px solid rgb(10, 221, 151);\n"
                                    "\n"
                                    "}\n"
                                    "\n"
                                    "#StartBtn::pressed {\n"
                                    "border: 2px solid #09B37B;\n"
                                    "}")
        self.StartBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imgs/StartBtnIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StartBtn.setIcon(icon)
        self.StartBtn.setIconSize(QtCore.QSize(20, 20))
        self.StartBtn.setObjectName("StartBtn")
        self.horizontalLayout_3.addWidget(self.StartBtn)
        self.SysMethBtn = QtWidgets.QPushButton(self.controlPanel)
        self.SysMethBtn.setMinimumSize(QtCore.QSize(213, 32))
        self.SysMethBtn.setMaximumSize(QtCore.QSize(213, 32))
        self.SysMethBtn.setStyleSheet("#SysMethBtn {\n"
                                      "/* Auto layout */\n"
                                      "\n"
                                      "display: flex;\n"
                                      "flex-direction: row;\n"
                                      "justify-content: center;\n"
                                      "align-items: center;\n"
                                      "padding: 0px 20px 0px 16px;\n"
                                      "spacing: 11px;\n"
                                      "\n"
                                      "width: 223px;\n"
                                      "height: 32px;\n"
                                      "\n"
                                      "/* control-default/typo-placeholder */\n"
                                      "\n"
                                      "border: 1px solid #0078D2;\n"
                                      "border-radius: 16px;\n"
                                      "\n"
                                      "\n"
                                      "font-family: \'Segoe UI\';\n"
                                      "font-style: normal;\n"
                                      "font-weight: 400;\n"
                                      "font-size: 14px;\n"
                                      "line-height: 32px;\n"
                                      "/* identical to box height, or 229% */\n"
                                      "\n"
                                      "display: flex;\n"
                                      "align-items: center;\n"
                                      "text-align: center;\n"
                                      "\n"
                                      "/* control-default/typo-placeholder */\n"
                                      "\n"
                                      "color: #0078D2;\n"
                                      "spacing:10px;\n"
                                      "}\n"
                                      "\n"
                                      "#SysMethBtn::hover {\n"
                                      "\n"
                                      "border: 1px solid rgb(0, 149, 255);\n"
                                      "color: rgb(0, 149, 255);\n"
                                      "}\n"
                                      "\n"
                                      "#SysMethBtn::pressed {\n"
                                      "border: 2px solid #0078D2;\n"
                                      "}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/imgs/StateBtnIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SysMethBtn.setIcon(icon1)
        self.SysMethBtn.setIconSize(QtCore.QSize(12, 12))
        self.SysMethBtn.setObjectName("SysMethBtn")
        self.horizontalLayout_3.addWidget(self.SysMethBtn)
        self.CreSampBtn = QtWidgets.QPushButton(self.controlPanel)
        self.CreSampBtn.setEnabled(True)
        self.CreSampBtn.setMinimumSize(QtCore.QSize(223, 32))
        self.CreSampBtn.setMaximumSize(QtCore.QSize(223, 32))
        self.CreSampBtn.setStyleSheet("#CreSampBtn {\n"
                                      "/* Auto layout */\n"
                                      "\n"
                                      "display: flex;\n"
                                      "flex-direction: row;\n"
                                      "justify-content: center;\n"
                                      "align-items: center;\n"
                                      "padding: 0px 20px 0px 16px;\n"
                                      "spacing: 11px;\n"
                                      "\n"
                                      "width: 223px;\n"
                                      "height: 32px;\n"
                                      "\n"
                                      "/* control-default/typo-placeholder */\n"
                                      "\n"
                                      "border: 1px solid #0078D2;\n"
                                      "border-radius: 16px;\n"
                                      "\n"
                                      "\n"
                                      "font-family: \'Segoe UI\';\n"
                                      "font-style: normal;\n"
                                      "font-weight: 400;\n"
                                      "font-size: 14px;\n"
                                      "line-height: 32px;\n"
                                      "/* identical to box height, or 229% */\n"
                                      "\n"
                                      "display: flex;\n"
                                      "align-items: center;\n"
                                      "text-align: center;\n"
                                      "\n"
                                      "/* control-default/typo-placeholder */\n"
                                      "\n"
                                      "color: #0078D2;\n"
                                      "spacing:10px;\n"
                                      "}\n"
                                      "\n"
                                      "#CreSampBtn::hover {\n"
                                      "\n"
                                      "border: 1px solid rgb(0, 149, 255);\n"
                                      "color: rgb(0, 149, 255);\n"
                                      "}\n"
                                      "\n"
                                      "#CreSampBtn::pressed {\n"
                                      "border: 2px solid #0078D2;\n"
                                      "}\n"
                                      "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/imgs/SampleBtnIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CreSampBtn.setIcon(icon2)
        self.CreSampBtn.setIconSize(QtCore.QSize(12, 12))
        self.CreSampBtn.setObjectName("CreSampBtn")
        self.horizontalLayout_3.addWidget(self.CreSampBtn)
        self.tasks_label = QtWidgets.QLabel(self.tab_3)
        self.tasks_label.setGeometry(QtCore.QRect(0, 126, 209, 30))
        self.tasks_label.setMinimumSize(QtCore.QSize(209, 30))
        self.tasks_label.setMaximumSize(QtCore.QSize(209, 30))
        self.tasks_label.setStyleSheet("/* Действия */\n"
                                       "\n"
                                       "\n"
                                       "width: 95px;\n"
                                       "height: 30px;\n"
                                       "\n"
                                       "/* XL */\n"
                                       "\n"
                                       "font-family: \'Inter\';\n"
                                       "font-style: normal;\n"
                                       "font-weight: 400;\n"
                                       "font-size: 20px;\n"
                                       "line-height: 150%;\n"
                                       "/* identical to box height, or 30px */\n"
                                       "\n"
                                       "\n"
                                       "\n"
                                       "/* bg/shadow */\n"
                                       "\n"
                                       "color: #002033;")
        self.tasks_label.setObjectName("tasks_label")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_hist = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_hist.setGeometry(QtCore.QRect(0, 74, 1381, 551))
        self.tableWidget_hist.setMinimumSize(QtCore.QSize(801, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget_hist.setFont(font)
        self.tableWidget_hist.setStyleSheet("#tableWidget_hist {\n"
                                            "/* Table */\n"
                                            "\n"
                                            "border: 1px solid rgba(0, 66, 105, 0.28);\n"
                                            "box-sizing: border-box;\n"
                                            "\n"
                                            "/* Auto layout */\n"
                                            "\n"
                                            "border-radius: 8px;\n"
                                            "/* control-default/bg-border */\n"
                                            "\n"
                                            "\n"
                                            "\n"
                                            "}\n"
                                            "\n"
                                            "#tableWidget_hist QHeaderView::section:first {\n"
                                            "\n"
                                            "border-top-left-radius: 8px;\n"
                                            "border-left: 1px solid rgba(0, 66, 105, 0.28);\n"
                                            "\n"
                                            "}\n"
                                            "\n"
                                            "#tableWidget_hist QHeaderView::section{\n"
                                            "/* S */\n"
                                            "\n"
                                            "font-family: \'Inter\';\n"
                                            "font-style: normal;\n"
                                            "font-weight: 400;\n"
                                            "font-size: 14px;\n"
                                            "line-height: 150%;\n"
                                            "\n"
                                            "\n"
                                            "color: #002033;\n"
                                            "\n"
                                            "\n"
                                            "height:58px;\n"
                                            "background: #FFFFFF;\n"
                                            "border-left: 0px solid rgba(0, 66, 105, 0.28);\n"
                                            "border-top: 1px solid rgba(0, 66, 105, 0.28);\n"
                                            "border-right: 1px solid rgba(0, 66, 105, 0.28);\n"
                                            "border-bottom: 1px solid rgba(0, 66, 105, 0.28);\n"
                                            "}\n"
                                            "\n"
                                            "#tableWidget_hist QHeaderView::section:last {\n"
                                            "\n"
                                            "border-top-right-radius: 8px;\n"
                                            "\n"
                                            "}\n"
                                            "\n"
                                            "")
        self.tableWidget_hist.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget_hist.setMidLineWidth(0)
        self.tableWidget_hist.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_hist.setAutoScrollMargin(12)
        self.tableWidget_hist.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_hist.setDragDropOverwriteMode(False)
        self.tableWidget_hist.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableWidget_hist.setAlternatingRowColors(True)
        self.tableWidget_hist.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_hist.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget_hist.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_hist.setWordWrap(True)
        self.tableWidget_hist.setCornerButtonEnabled(False)
        self.tableWidget_hist.setRowCount(1)
        self.tableWidget_hist.setObjectName("tableWidget_hist")
        self.tableWidget_hist.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_hist.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_hist.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_hist.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_hist.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_hist.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_hist.setHorizontalHeaderItem(5, item)
        self.tableWidget_hist.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_hist.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget_hist.horizontalHeader().setMinimumSectionSize(10)
        self.tableWidget_hist.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_hist.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_hist.verticalHeader().setVisible(False)
        self.tasks_label_hist = QtWidgets.QLabel(self.tab_4)
        self.tasks_label_hist.setGeometry(QtCore.QRect(0, 28, 209, 30))
        self.tasks_label_hist.setMinimumSize(QtCore.QSize(209, 30))
        self.tasks_label_hist.setMaximumSize(QtCore.QSize(209, 30))
        self.tasks_label_hist.setStyleSheet("/* Действия */\n"
                                            "\n"
                                            "\n"
                                            "width: 95px;\n"
                                            "height: 30px;\n"
                                            "\n"
                                            "/* XL */\n"
                                            "\n"
                                            "font-family: \'Inter\';\n"
                                            "font-style: normal;\n"
                                            "font-weight: 400;\n"
                                            "font-size: 20px;\n"
                                            "line-height: 150%;\n"
                                            "/* identical to box height, or 30px */\n"
                                            "\n"
                                            "\n"
                                            "\n"
                                            "/* bg/shadow */\n"
                                            "\n"
                                            "color: #002033;")
        self.tasks_label_hist.setObjectName("tasks_label_hist")
        self.tabWidget.addTab(self.tab_4, "")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1440, 64))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(1440, 64))
        self.frame.setMaximumSize(QtCore.QSize(1440, 64))
        self.frame.setStyleSheet("border-bottom: 1px solid #ECF1F4;\n"
                                 "\n"
                                 "\n"
                                 "height: 64px;\n"
                                 "width: 1440px;")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(24, 0, 31, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_label.sizePolicy().hasHeightForWidth())
        self.logo_label.setSizePolicy(sizePolicy)
        self.logo_label.setMinimumSize(QtCore.QSize(99, 55))
        self.logo_label.setMaximumSize(QtCore.QSize(99, 55))
        self.logo_label.setStyleSheet("image: url(:/imgs/logo-gazprom-neft.png);\n"
                                      "padding-bottom: 8px;\n"
                                      "padding-top: 1px;\n"
                                      "border: 0px;")
        self.logo_label.setText("")
        self.logo_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.logo_label.setObjectName("logo_label")
        self.horizontalLayout.addWidget(self.logo_label)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 22, 0, 28)
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.user_label = QtWidgets.QLabel(self.frame_2)
        self.user_label.setMinimumSize(QtCore.QSize(70, 16))
        self.user_label.setMaximumSize(QtCore.QSize(70, 16))
        self.user_label.setSizeIncrement(QtCore.QSize(100, 100))
        self.user_label.setStyleSheet("width: 75px;\n"
                                      "height: 14px;\n"
                                      "border:0px;\n"
                                      "font-family: \'Inter\';\n"
                                      "font-style: normal;\n"
                                      "font-weight: 400;\n"
                                      "font-size: 12px;\n"
                                      "line-height: 110%;\n"
                                      "/* identical to box height, or 13px */\n"
                                      "\n"
                                      "\n"
                                      "/* typo/secondary */\n"
                                      "\n"
                                      "color: rgba(0, 32, 51, 0.6);\n"
                                      "padding:0px;\n"
                                      "margin:0px;\n"
                                      "spacing:0px;")
        self.user_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.user_label.setObjectName("user_label")
        self.horizontalLayout_2.addWidget(self.user_label)
        self.exit_pushButton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_pushButton.sizePolicy().hasHeightForWidth())
        self.exit_pushButton.setSizePolicy(sizePolicy)
        self.exit_pushButton.setMinimumSize(QtCore.QSize(16, 16))
        self.exit_pushButton.setMaximumSize(QtCore.QSize(16, 16))
        self.exit_pushButton.setStyleSheet("#exit_pushButton{\n"
                                           "\n"
                                           "\n"
                                           "border: 0px;\n"
                                           "background: rgb(255, 255, 255);\n"
                                           "\n"
                                           "}\n"
                                           "#exit_pushButton::hover{\n"
                                           "background: rgb(205, 238, 255);\n"
                                           "\n"
                                           "}\n"
                                           "\n"
                                           "#exit_pushButton::pressed{\n"
                                           "\n"
                                           "border: 4px solid rgb(139, 205, 255);\n"
                                           "}")
        self.exit_pushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/imgs/IconExit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_pushButton.setIcon(icon3)
        self.exit_pushButton.setIconSize(QtCore.QSize(16, 16))
        self.exit_pushButton.setObjectName("exit_pushButton")
        self.horizontalLayout_2.addWidget(self.exit_pushButton, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignRight)
        WorkWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WorkWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 26))
        self.menubar.setObjectName("menubar")
        WorkWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WorkWindow)
        self.statusbar.setObjectName("statusbar")
        WorkWindow.setStatusBar(self.statusbar)

        self.retranslateUi(WorkWindow)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WorkWindow)

    def retranslateUi(self, WorkWindow):
        _translate = QtCore.QCoreApplication.translate
        WorkWindow.setWindowTitle(_translate("WorkWindow", "Рабочее окно"))
        self.statusHeader_label.setText(_translate("WorkWindow", "Статус устройств"))
        self.Controller_label.setToolTip(_translate("WorkWindow", "Информация о контроллере"))
        self.Controller_label.setStatusTip(_translate("WorkWindow", "Информация о контроллере"))
        self.Controller_label.setText(_translate("WorkWindow", "Контроллер анализатора"))
        self.cellTemp_label.setToolTip(_translate("WorkWindow", "Информация о температуре ячейки1"))
        self.cellTemp_label.setStatusTip(_translate("WorkWindow", "Информация о температуре ячейки2"))
        self.cellTemp_label.setText(_translate("WorkWindow", "Регулятор температуры ячейки"))
        self.outerTemp_label.setToolTip(_translate("WorkWindow", "Информация о температуре регулятора внешней трубки1"))
        self.outerTemp_label.setStatusTip(
            _translate("WorkWindow", "Информация о температуре регулятора внешней трубки2"))
        self.outerTemp_label.setText(_translate("WorkWindow", "Регулятор температуры внешней трубки"))
        self.innerTemp_label.setToolTip(
            _translate("WorkWindow", "Информация о температуре регулятора внутренней трубки1"))
        self.innerTemp_label.setStatusTip(
            _translate("WorkWindow", "Информация о температуре регулятора внутренней трубки2"))
        self.innerTemp_label.setText(_translate("WorkWindow", "Регулятор температуры внутренней трубки"))
        self.sampler_label.setToolTip(_translate("WorkWindow", "Информация об устройстве ввода проб1"))
        self.sampler_label.setStatusTip(_translate("WorkWindow", "Информация об устройстве ввода проб2"))
        self.sampler_label.setText(_translate("WorkWindow", "Устройство ввода проб"))
        self.CLMeter_label.setToolTip(_translate("WorkWindow", "Информация о кулонометре1"))
        self.CLMeter_label.setStatusTip(_translate("WorkWindow", "Информация о кулонометре2"))
        self.CLMeter_label.setText(_translate("WorkWindow", "Кулонометр"))
        self.ControllerIndicator_label.setToolTip(_translate("WorkWindow", "Информация о контроллере"))
        self.ControllerIndicator_label.setStatusTip(_translate("WorkWindow", "Информация о контроллере"))
        self.outerTempIndicator_label.setToolTip(
            _translate("WorkWindow", "Информация о температуре регулятора внешней трубки1"))
        self.outerTempIndicator_label.setStatusTip(
            _translate("WorkWindow", "Информация о температуре регулятора внешней трубки2"))
        self.innerTempIndicator_label.setToolTip(
            _translate("WorkWindow", "Информация о температуре регулятора внутренней трубки1"))
        self.innerTempIndicator_label.setStatusTip(
            _translate("WorkWindow", "Информация о температуре регулятора внутренней трубки2"))
        self.cellTempIndicator_label.setToolTip(_translate("WorkWindow", "Информация о температуре ячейки1"))
        self.cellTempIndicator_label.setStatusTip(_translate("WorkWindow", "Информация о температуре ячейки2"))
        self.samplerIndicator_label.setToolTip(_translate("WorkWindow", "Информация об устройстве ввода проб1"))
        self.samplerIndicator_label.setStatusTip(_translate("WorkWindow", "Информация об устройстве ввода проб2"))
        self.CLMeterIndicator_label.setToolTip(_translate("WorkWindow", "Информация о кулонометре1"))
        self.CLMeterIndicator_label.setStatusTip(_translate("WorkWindow", "Информация о кулонометре2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("WorkWindow", "Статус системы"))
        self.devices_label.setText(_translate("WorkWindow", "Устройства"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("WorkWindow", "Печь"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("WorkWindow", "Кулонометр"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("WorkWindow", "Автосемплер"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2),
                                  _translate("WorkWindow", "Визуальный статус устройств"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("WorkWindow", "   Описание"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("WorkWindow", "Состояние"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("WorkWindow", "   Время создания"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("WorkWindow", "   Запуск отсчета времени"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("WorkWindow", "   Время остановки"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("WorkWindow", "   Общее время"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("WorkWindow", "   Действие"))
        self.actions_label.setText(_translate("WorkWindow", "Действия"))
        self.label.setText(_translate("WorkWindow", "Выберите строку чтобы применить действие"))
        self.SysMethBtn.setText(_translate("WorkWindow", "Выбрать режим работы"))
        self.CreSampBtn.setText(_translate("WorkWindow", "Создать группу образцов"))
        self.tasks_label.setText(_translate("WorkWindow", "Последние задачи"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("WorkWindow", "Диспетчер задач"))
        self.tableWidget_hist.setSortingEnabled(False)
        item = self.tableWidget_hist.horizontalHeaderItem(0)
        item.setText(_translate("WorkWindow", "Номер"))
        item = self.tableWidget_hist.horizontalHeaderItem(1)
        item.setText(_translate("WorkWindow", "Дата"))
        item = self.tableWidget_hist.horizontalHeaderItem(2)
        item.setText(_translate("WorkWindow", "Наименование"))
        item = self.tableWidget_hist.horizontalHeaderItem(3)
        item.setText(_translate("WorkWindow", "Результат 1"))
        item = self.tableWidget_hist.horizontalHeaderItem(4)
        item.setText(_translate("WorkWindow", "Результат 2"))
        item = self.tableWidget_hist.horizontalHeaderItem(5)
        item.setText(_translate("WorkWindow", "Длительность"))
        self.tasks_label_hist.setText(_translate("WorkWindow", "Последние задачи"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("WorkWindow", "История"))
        self.user_label.setText(_translate("WorkWindow", "Lab manager"))


from mplwidget import MplWidget
import resources

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    WorkWindow = QtWidgets.QMainWindow()
    ui = Ui_WorkWindow()
    ui.setupUi(WorkWindow)
    WorkWindow.show()
    sys.exit(app.exec_())
